# -*- mode: ruby -*-

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "debian-9.6.0-xen"

  # define a custom network, then put nic in promiscuous mode to ensure  it
  # can be accessed from host
  config.vm.network :private_network, type: "dhcp"
  #, auto_config: false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    # enable promiscuous mode on the private network
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
  end

  config.vm.provision "shell", path: "../scripts/packages.sh"
  config.vm.provision "shell", path: "../scripts/xen.sh"
  config.vm.provision "shell", path: "../scripts/networking.sh"
  config.vm.provision "shell", path: "../scripts/opam.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/mirage.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/finish.sh"


  config.vm.synced_folder "/Users/anmonteiro/Documents/github/mirage-platform", "/home/vagrant/mirage-platform", type:"rsync"
  config.vm.synced_folder "/Users/anmonteiro/Documents/github/mirageplay/httpaf", "/app", type:"rsync"
  config.vm.synced_folder "/Users/anmonteiro/Documents/github/ocaml-h2", "/app", type:"rsync"
end
